CUDA_VISIBLE_DEVICES=0 llamafactory-cli train \
    --stage sft \
    --do_train \
    --model_name_or_path /mnt/HDD/mlk_workspace/chatglm3-6b \
    --dataset train \
    --dataset_dir ./saves/gpt-4o-mini/docred/fine_tuning_for_description_extraction \
    --template chatglm3 \
    --finetuning_type lora \
    --output_dir ./saves/gpt-4o-mini/docred/student_model_checkpoints/chatglm3-6b \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 8192 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine \
    --logging_steps 50 \
    --save_strategy epoch \
    --num_train_epochs 1 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.03 \
    --val_size 0 \
    --plot_loss \
    --max_new_tokens 8192 \
    --load_best_model_at_end False \
    --bf16 \
    --trust_remote_code True
